# Generated by Django 4.2.5 on 2023-11-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ssl_settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssl_ports', models.CharField(max_length=255)),
                ('expiry_date_check', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='domainlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('sans', models.TextField()),
                ('ssl_issuer_organization', models.CharField(max_length=255, null=True)),
                ('ssl_issuer_common_name', models.CharField(max_length=255, null=True)),
                ('expires', models.CharField(max_length=255, null=True)),
                ('days_left', models.CharField(max_length=50, null=True)),
                ('domain_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=50, null=True)),
                ('last_updated', models.CharField(max_length=50, null=True)),
                ('contact_users', models.ManyToManyField(to='ssltracker.contacts')),
            ],
        ),
    ]
