# Generated by Django 4.2.5 on 2023-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='middle_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
