# Generated by Django 4.2.5 on 2023-11-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0003_customgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssl_logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.CharField(max_length=255)),
                ('log_time', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('log_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='domainlist',
            name='domain_type',
        ),
        migrations.AddField(
            model_name='domainlist',
            name='certLocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domainlist',
            name='ipAddress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
