# Generated by Django 4.2.5 on 2023-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0004_ssl_logs_remove_domainlist_domain_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='digicert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('validated_until', models.CharField(max_length=255, null=True)),
                ('last_updated', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='domainlist',
            name='digi_cert',
            field=models.BooleanField(default=False),
        ),
    ]
