# Generated by Django 4.2.5 on 2023-11-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0005_digicert_domainlist_digi_cert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainlist',
            name='digi_cert',
        ),
    ]
