# Generated by Django 4.2.5 on 2023-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0006_remove_domainlist_digi_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssl_settings',
            name='digicert_api_key',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='ssl_settings',
            name='msgraph_client_id',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='ssl_settings',
            name='msgraph_client_secret',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='ssl_settings',
            name='msgraph_tenant_id',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
