# Generated by Django 4.2.5 on 2023-12-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0007_ssl_settings_digicert_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digicert',
            old_name='domain_id',
            new_name='cert_id',
        ),
        migrations.RenameField(
            model_name='digicert',
            old_name='domain_name',
            new_name='cn',
        ),
        migrations.RenameField(
            model_name='digicert',
            old_name='validated_until',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='digicert',
            name='sans',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='digicert',
            name='valid_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ssl_settings',
            name='digicert_account_id',
            field=models.CharField(default='digi cert account id', max_length=255),
        ),
        migrations.AddField(
            model_name='ssl_settings',
            name='digicert_api_url',
            field=models.CharField(default='digi cert api url', max_length=255),
        ),
        migrations.AlterField(
            model_name='ssl_settings',
            name='digicert_api_key',
            field=models.CharField(default='digi cert api key', max_length=255),
        ),
        migrations.AlterField(
            model_name='ssl_settings',
            name='msgraph_client_id',
            field=models.CharField(default='MSGRAPH client ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='ssl_settings',
            name='msgraph_client_secret',
            field=models.CharField(default='MSGRAPH client secret', max_length=255),
        ),
        migrations.AlterField(
            model_name='ssl_settings',
            name='msgraph_tenant_id',
            field=models.CharField(default='MSGRAPH tenant ID', max_length=255),
        ),
    ]
