# Generated by Django 4.2.5 on 2023-12-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0008_rename_domain_id_digicert_cert_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssl_settings',
            name='msgraph_api_url',
            field=models.CharField(default='MSGRAPH API URL', max_length=255),
        ),
    ]
