# Generated by Django 4.2.5 on 2023-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0009_ssl_settings_msgraph_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssl_settings',
            name='msgraph_api_version',
            field=models.CharField(default='v1.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='ssl_settings',
            name='digicert_api_url',
            field=models.CharField(default='https://daas.digicert.com/apicontroller/v1/certificate/list', max_length=255),
        ),
        migrations.AlterField(
            model_name='ssl_settings',
            name='msgraph_api_url',
            field=models.CharField(default='https://graph.microsoft.com', max_length=255),
        ),
    ]
