# Generated by Django 4.2.5 on 2023-12-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0010_ssl_settings_msgraph_api_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digicert',
            old_name='sans',
            new_name='san',
        ),
    ]
