# Generated by Django 4.2.5 on 2023-12-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0011_rename_sans_digicert_san'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digicert',
            name='san',
            field=models.TextField(blank=True, null=True),
        ),
    ]
