# Generated by Django 4.2.5 on 2023-12-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0012_alter_digicert_san'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlist',
            name='sans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
