# Generated by Django 4.2.5 on 2023-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0013_alter_domainlist_sans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainlist',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
