# Generated by Django 5.2.18 on 2026-10-09 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssltracker', '0014_alter_domainlist_domain_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_slot', models.PositiveSmallIntegerField(editable=False, null=True, unique=True)),
                ('mode', models.CharField(default='all', max_length=12)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ssltracker.domainlist')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ssltracker.scanrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_slot', 1), ('active_slot__isnull', False), ('status__in', ['queued', 'running'])), models.Q(('active_slot__isnull', True), ('status__in', ['completed', 'failed'])), _connector='OR'), name='scan_run_active_state'),
        ),
    ]
